name = "d365-widget-collab"
main = "collab-worker.js"
compatibility_date = "2024-12-19"

# Create KV namespace first:
# npx wrangler kv:namespace create "ROOMS"
# Then paste the id below

[[kv_namespaces]]
binding = "ROOMS"
id = "43c05060066549f7a4408d7d02befc73"
